language: java
jdk:
  - openjdk8

script: mvn clean install

cache:
  directories:
    - node_modules

after_success:
  - mvn clean test jacoco:report coveralls:report

services:
  - docker

before_install:
  - docker build -t $DOCKER_IMAGE .

# cf. https://docs.travis-ci.com/user/docker/#branch-based-registry-pushes
deploy:
  provider: script
  script: bash docker_push
  on: heroku