

version: "3.1"
services:
 dbpostgresql:
  image: postgres:12-alpine
  environment:
   POSTGRES_DB: 'yaqari_db'
   POSTGRES_HOST_AUTH_METHOD: 'trust' # allow no password
 app:
  #container_name: registry.heroku.com/projet-ivvq/web
  image: registry.heroku.com/projet-ivvq/web
  build:
   context: ./
   dockerfile: Dockerfile
  ports:
  - "4200:80"
  depends_on:
    - dbpostgresql