version: "3.1"
services:
 dbpostgresql:
  image: postgres:12-alpine
  ports:
   - '5432:5432'
  environment:
   POSTGRES_DB: 'yaqari_db'
   POSTGRES_HOST_AUTH_METHOD: 'trust' # allow no password
 app:
  container_name: registry.heroku.com/projet-ivvq/web
  image: registry.heroku.com/projet-ivvq/web
  build: ./
  ports:
  - "8080:8080"
  depends_on:
    - dbpostgresql