

version: "3.1"
services:
 dbpostgresql:
  image: postgres:12-alpine
  environment:
   POSTGRES_DB: 'yaqari_db'
   POSTGRES_HOST_AUTH_METHOD: 'trust' # allow no password
 app:
  image: $DOCKER_IMAGE
  build:
   context: ./
   dockerfile: Dockerfile
  ports:
  - "8080:8080"
  depends_on:
    - dbpostgresql